updated function app

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,33 +65,28 @@ jobs:
 
       # --- Azure Login for Function App Job (using OpenID Connect) ---
       # This login is also sufficient for ACR authentication if configured correctly
-      - name: Docker Login to ACR
-        uses: azure/docker-login@v1
+      - name: 🚀 Azure Login
+        uses: azure/login@v2
         with:
-          login-server: ${{ env.ACR_LOGIN_SERVER }}
-          username: ${{ secrets.ACR_LOGIN_SERVER.clientId }}    # <--- Add this line
-          password: ${{ secrets.ACR_LOGIN_SERVER.clientSecret }} # <--- Add this line
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+      
+      - name: Login to ACR
+        run: az acr login --name personalproject    
 
       - name: Change directory to Function App
         run: cd WeatherForecast.Function/
 
-      - name: Build Azure Function Docker image
-        run: |
-          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
+      - name: Build Docker image
+        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/weatherforecast:latest .
 
-      - name: Tag Azure Function Docker image as 'latest'
-        run: docker tag ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:latest
+      - name: Push Docker image to ACR
+        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/weatherforecast:latest    
 
-      - name: Push Azure Function Docker image to ACR
-        run: |
-          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
-          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:latest
-
-      - name: Clean up Function Docker images (optional)
-        if: always()
-        run: |
-          docker rmi ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:${{ env.IMAGE_TAG }} || true
-          docker rmi ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:latest || true
+      # - name: Clean up Function Docker images (optional)
+      #   if: always()
+      #   run: |
+      #     docker rmi ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:${{ env.IMAGE_TAG }} || true
+      #     docker rmi ${{ env.ACR_LOGIN_SERVER }}/${{ env.FUNCTION_IMAGE_NAME }}:latest || true
 
       - name: Deploy Azure Function App from Docker Image
         uses: azure/functions-action@v1
